reasoning_common_qwen3:
  reasoning_parser: "qwen3"
  version: "1"

ignore_reasoning_tag_common:
  reasoning_parser: "ignore"
  version: "1"

deepseek_r1_common:
  reasoning_parser: "deepseek_r1"
  version: "1"

deepseek_r1_markup_common:
  reasoning_parser: "deepseek_r1_markup"
  version: "1"

reasoning-stochastic_common_qwen3:
  reasoning_parser: "qwen3"
  temperature: 0.6
  top_p: 0.95 
  version: "1"

reasoning-stochastic_common_gptoss:
  temperature: 0.6
  top_p: 0.95
  version: "1"

reasoning-stochastic_common_gptoss_swallow_rl:
  temperature: 1.0
  top_p: 1.0
  version: "1"
